### ISSUE TITLE
Clicking the tile of the Spotify extension opens the documentation

### ISSUE THREAD

**Issue by savaka2** [LLK/scratchx#113]
I can't find a link that opens the actual Spotify extension (not through a demo project)

**Comment by ericrosenbaum** [comment]
Sorry about the confusion- I wanted to make sure people see the docs, since they are pretty extensive and include a video. I know this makes it inconsistent with other extensions- sorry about that.

Also, sorry it was hard to find the link for a blank project with the extension loaded. It is in the "details" section at the bottom. I've moved the "blank project" link to the top of that section.

**Comment by savaka2** [comment]
Thanks, I thought it might be intentional but probably not but it is
