### ISSUE TITLE
When Will Scratchx Cease to be "Experimental"?

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratchx#118]
Hi,
   The reason I'm asking this is I've been teaching computing with hardware extensions for years now and I'd like to see an end to the dialog boxes giving the warning. It'd be one less thing to click on. Also, it
could give the impression that Scratchx is new and unstable and may not be around for long.

**Comment by rschamp** [comment]
Hi @CreativeComputerLab thanks for your question. When the extension system in Scratch 3.0 is released, ScratchX will be deprecated. The warnings are due to the architecture of ScratchX, so would be irresponsible to remove for new users. In 3.0, extensions will be properly sandboxed, so will not require any warnings.
