### ISSUE TITLE
What's the link for using localstorage_extension.js

### ISSUE THREAD

**Issue by egottardo** [LLK/scratchx#120]
I am trying to use the localstorage_extension.js extension using the link https://github.com/LLK/scratchx/blob/master/localstorage_extension.js, but the extension does not appear in the "more blocks" list of scratchx.
What is the correct link to use?

Thanks for any help.

**Comment by mkacct** [comment]
That is the blob page, not the actual file. Since it is not on a GitHub Pages site, you can use RawGit to get a URL, [click here](http://scratchx.org/?url=https://cdn.rawgit.com/LLK/scratchx/master/localstorage_extension.js) or copy and paste this: https://cdn.rawgit.com/LLK/scratchx/master/localstorage_extension.js

**Comment by egottardo** [comment]
Thank You @savaka2!! With this link I get the block in the Scratchx, but I could not make it work. I'm trying to save a .txt logfile in a local hard drive. There is some example or documentation explaining how to use localstorage_extension.js?
Thanks in advance..
