### ISSUE TITLE
Can't save project from Firefox

### ISSUE THREAD

**Issue by rileyjshaw** [LLK/scratchx#161]
Firefox Developer Edition, 66.0b12 (64-bit)
MacOS Mojave, 10.14.3 (18D109)

When trying to save, I get the following error in the console:

```
10:39:39 AM | err | [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2038"]
```

**Comment by towerofnix** [comment]
Unfortunately I think this is a change in how Firefox works with Flash, since I know I used to be able to save ScratchX files and I can't anymore (same error). In order to workaround it in [s2online](https://s2online.github.io/) (a Scratch 2.0 mod for loading existing projects into 2.0), I had to [create an external JS function](https://github.com/s2online/s2online.github.io/commit/82a3de695c27bf91b98705488f64190bd804ca93#diff-7a9076d6d94e62c13d641aa71f19ae8e) and [call that instead of using Flash's builtin file download tool](https://github.com/s2online/s2online.github.io/commit/82a3de695c27bf91b98705488f64190bd804ca93#diff-1f0d5009d0906d51e47b358cfd282753). But I don't think ScratchX's SWF is open source, so you might have trouble making a fix yourself (and ScratchX is in maintenance mode / being phased out, with 3.0's extension system on the rise, so the ST likely won't get around to fixing this).
