### ISSUE TITLE
No error message when Flash is unavailable

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratchx#34]
If the user doesn't have Flash installed, then the buttons on the ScratchX homepage just seem to not do anything. It would be nice to show an error message somewhere to let the user know why things are broken.

**Comment by qingzhengzhuma** [comment]
but in my computer（Ubuntu 14.04 LTS），i have installed the flash plugin，the ScratchX homepage still do nothing，can anyone help me？

**Comment by MrYsLab** [comment]
@qingzhengzhuma Are you using Firefox? If so, try chrome. This is a long known and ignored issue. (issue #24). Linux is a second class citizen when it comes to Scratch :-(.

**Comment by qingzhengzhuma** [comment]
Thanks a lot， I have tried Chromium，and it doesn't work either...╮(╯▽╰)╭，and then I found that the Scratch Extension plugin only works with mac and win，is this the reason？@MrYsLab

**Comment by MrYsLab** [comment]
Yes the plugin does not work for linux (linux is truly second class in the minds of the Scratch developers), which is why I wrote [Xi](https://github.com/MrYsLab/xi) that uses a server. I also have some applications that use the off-line editor - [s2aio](https://github.com/MrYsLab/s2aio/wiki) and [s2a_fm](https://github.com/MrYsLab/s2a_fm).

**Comment by colbygk** [comment]
@MrYsLab the Scratch developers are a small and extremely committed team. Our entire backend infrastructure is based on Linux. I personally have contributed to many Linux focused projects since 1994. We care deeply about Linux.  We also work to support all of the community of Scratch users and there is only so much time during the day to do this. The beauty of open source is that anyone can contribute a fix or ideas about how to fix an issue that person wants solved.

**Comment by MrYsLab** [comment]
@colbygk I am happy to hear that the Scratch team is deeply committed to linux, but whenever I ask linux questions or enter linux issues, they seem to go unnoticed. Just saying ;-)
