### ISSUE TITLE
(function (ext) ? Is that a valid code?

### ISSUE THREAD

**Issue by Rumanti** [LLK/scratchx#42]
The boilerplate code in the developer documentation starts with
(function (ext) {
and because Brackets kept giving me errors about it, I removed the first left bracket. However, bad things happen since I removed it, and I began to wonder, is that a valid code? There is no closing bracket for the first left bracket. Google search reveals nothing.

Thanks.

**Comment by djdolphin** [comment]
All the brackets are eventually closed.
````
(function(ext) {
1        2   2 3

})({});
314554
````

**Comment by Rumanti** [comment]
Okay, thanks!

**Comment by bleush38p** [comment]
Just for the record, and because it will make you a better programmer, this is called an [Immediately Invoked Function Expression](http://benalman.com/news/2010/11/immediately-invoked-function-expression/), or IIFE. There's plenty of reasons to use them, most having to do with scope and "private" variables/properties. Basically, you're creating a function expression, and immediately invoking it - hence the name.
```js
(function() { ... })()
```
As you can see, a function is created `(function() { ... })` and invoked: `()`. In this particular use, `{}` is passed as a argument and put in the local variable ext. There's no specific reason that you couldn't just define ext on the inside (although, I will admit, it does look pretty.) One place you'll see IIFEs often used is to reclaim a variable used in the global namespace, and often to ensure `undefined` means what you think it will. For example:
```js
(function($, undefined) {
  ...
}(jQuery))
```
This gives you an easy way to use jQuery as `$` if `jQuery.noConflict` has been called, or if something else took over the `$` object. Additionally, it sets `undefined` to `undefined`, because no argument was passed to it. This means that even if some especially annoying bit of code has changed `undefined` to, say, `"not undefined lol"` - and this does happen! - your code will still work properly. In fact, speaking of jQuery, if you take a look at the code, you'll notice that it's wrapped in an IIFE as well. The minified version is wrapped in `!function(){ ... }()` - which saves one byte from the parenthetical method, and works if you don't care about the return value.

Lastly they let you use variables internally that aren't exposed to anything on the outside. Here's an example from the site I linked earlier:
```js
var counter = (function() {
  var i = 0
  return {
    get: function() {
      return i
 }, set: function (val) {
      i = val
 }, increment: function() {
      return ++i
    }
  }
}())
// counter is set to the object returned inside the IIFE
counter.get() // 0
counter.set(3)
counter.increment() // 4
counter.increment() // 5
counter.i // undefined // `i` isn't a property of the object
i // ReferenceError: i is not defined // it only exists inside the closure.
```

**Comment by Rumanti** [comment]
Thanks for all the explanation @bleush38p :smile: I have never heard of IIFE, so your explanation really helps! I was wondering what those extra pair of brackets doing there :sweat_smile:
