### ISSUE TITLE
Sprite library broke?

### ISSUE THREAD

**Issue by sayamindu** [LLK/scratchx#60]
Looks like the sprite library does not show anything on the scratchx.org site (open up any project or the editor, and click on the sprite library dialog).

Didn't see anything obvious in the browser console.

**Comment by programitra** [comment]
I have run into this issue too. I have a workshop going where I am introducing my sensor board's ScratchX extension to students in the next couple of days. So, wondering what timeline would resolution of this issue have. Currently, the workaround is to export sprites from offline scratch 2.0 editors and importing / importing from the filesystem / drawing your own sprites.

**Comment by rschamp** [comment]
This is due to the editor requesting the media library via http://scratch.mit.edu, which triggers a request by the swf to get crossdomain.xml. Since we now force SSL, the crossdomain.xml request is redirected, and Flash doesn't accept that response. We will start requesting the media library through femto.media.mit.edu instead, which doesn't require SSL, with the longterm plan being to move scratchx.org to SSL (complicated because it's hosted on Github pages).

**Comment by thisandagain** [comment]
Looks like this was actually isolated to `http(s)://cdn.scratch.mit.edu` and related to some CDN configuration changes we made there. I have deployed a patch and this appears to be resolved.

**Comment by kaschm** [comment]
:+1: thank you @thisandagain !

**Comment by kaspesla** [comment]
Yay!
