### ISSUE TITLE
Odd caching behavior with async reporters embedded in blocks that wait

### ISSUE THREAD

**Issue by sayamindu** [LLK/scratchx#61]
Steps to reproduce:

1. Load https://www.wolframcloud.com/objects/0c800177-ce1f-4ddb-95f9-b61974f9d705.js via "Open Extension URL"
2. Add a sprite
3. Pull out the say _ for 2 second block and put the extension block (population of __) into it
4. Run the block by clicking on it - the sprite should say 3125790 (around 3 million)
5. Change the input country to India, and run the block again. The sprite says the population of Armenia again.

Expected result:
The sprite should say 1291780156 (around 1.3 billion)

**Comment by cwillisf** [comment]
The extension is calling its callback with the correct value, but the "say" block is displaying the stale value before the extension calls the callback.

**Comment by cwillisf** [comment]
It turns out that this is an "optimization" that Scratch performs. Here's the sequence of events:

1. The user clicks the "say { population of { armenia } } for { 2 } secs" stack.
2. The "say" block requests a value from the "population" block.
3. The "population" block doesn't have a value ready, so Scratch execution of this thread is suspended until a value becomes available.
4. Scratch calls `wolframCloudFunc1('armenia', callback)` within the extension.
5. The extension calls `callback` with a value of `"3125790"`.
6. Scratch marks the "population" block as having a value ready. Since execution was waiting for this block, the thread resumes.
7. The "say" block consumes the "population" block's value; the "population" block is now marked as not having a value ready.
8. As an optimization, Scratch calls `wolframCloudFunc1('armenia', callback)` within the extension again so that a value will be ready immediately next time.
9. The "say" block displays "3125790".
10. The extension calls `callback` with a value of `"3125790"` again.
11. Scratch marks the "population" block as having a value ready.
12. The user changes the "population" block to contain "india".
13. The user clicks the "say { population of { india } } for { 2 } secs" stack.
14. The "say" block requests a value from the "population" block.
15. The "population" block already has a value ready, so it returns `"3125790"` immediately.
16. The "say" block displays "3125790".
17. Scratch calls `wolframCloudFunc1('india', callback)` so that a value will be ready for next time.
18. The extension calls `callback` with a value of `"1291780156"`.

This "optimization" works well in a limited number of situations, but not in cases like this where a Requester block's value may change significantly from one call to the next.

One thing we could do to fix this particular case would be to make Scratch discard a Requester's cached value if any of its arguments have changed. However, we'd still get stale values in situations where a value could change significantly over time without a parameter change.

In my opinion, the most correct fix here would be to stop preemptively caching values from an extension Requester block altogether. This could have a significant performance impact on some extension projects, but I think it's the only way to provide correct Requester behavior in extensions.

An extension can always choose to memoize results internally if that's appropriate in their particular situation. For example, memoization would work well for country populations, but might be inappropriate when reading hardware sensors.

**Comment by cwillisf** [comment]
It turns out I was partially wrong: the behavior is as I described, but I misunderstood the intent. The Requester value is being cached, but it's not happening as the result of an intended optimization. Instead, it's a side effect of the way that the "say" block is processed.

The "say" block is actually executed more than once. The first time (`interp.activeThread.firstTime`) it shows a speech bubble and sets a timer (`interp.startTimer(secs)`). Later, it checks the timer and speech bubble ownership, then removes the speech bubble if appropriate.

The problem stems from the fact that the interpreter runs `checkBlockingArgs(b)` each time (see `evalCmd(b:Block)`). Since the interpreter doesn't know that the "say" block won't attempt to access its parameter when `interp.activeThread.firstTime` is false it assumes that the Requester must have a value before processing the "say" block the second time around: `checkBlockingArgs(b)` therefore causes the Requester to be processed and the "bad" value is stored, but not consumed.

I think the best fix for this would be pretty invasive: the check for blocking arguments should be merged into the functionality of a block, but not necessarily into `interp.arg(b, ...)`. It should be done in such a way that (for example) a block with two arguments could cause two Requesters could be queried before the interpreter yields once, whereas just throwing a "maybe yield" into `interp.arg(b, ...)` would lead to a query-yield-query-yield pattern. The key is that it should be up to the block to decide whether or not to evaluate its arguments rather than the interpreter automatically evaluating them ahead of time, but arguments that are going to be evaluated should be evaluated as early as possible so that their delays (if Requesters) can overlap.

I don't think such an invasive change is a good idea right now, so I'm going to look into resetting a Requester's state if its arguments have changed. This will lead to correct behavior at the project level, though with blocks like "say {} for {} secs" the Requester will be evaluated at least one unnecessary time.

**Comment by TheLogFather** [comment]
Curious to know how https://github.com/LLK/scratch-flash/pull/795 impacts on this...?
( And any thoughts about my final question in my last comment there?
...I guess I should actually do some work to clean up the things we talked about there, but I'd also been hoping to get a more definitive answer to my question about the current code yielding at zero request state: https://github.com/LLK/scratch-flash/pull/795#discussion_r38577546. )

**Comment by cwillisf** [comment]
@TheLogFather it's been a while since I thought about LLK/scratch-flash#795 but I think you're right to wonder about an interaction. Specifically, if the requester goes from 2 to 0 because of the code in this PR, then your code would need to find out somehow in order to keep the blocking count accurate. That doesn't feel very clean to me... further evidence that this isn't really the best fix, IMO.

On the other hand, I suspect that getting rid of `checkBlockingArgs` as I suggested would take even more work than your changes in LLK/scratch-flash#795. Such a large change might have to wait for the next version of Scratch...
