### ISSUE TITLE
Wiki: command blocks that wait - poss clarify?

### ISSUE THREAD

**Issue by darren-a** [LLK/scratchx#68]
Current text:

// Functions for block with type 'w' will get a callback function as the 
// final argument. This should be called to indicate that the block can
// stop waiting.

It seems to me that this block itself isn't waiting as much as the runtime is waiting for this block to do its job, no?

Would it be right to say something like this:

// The invocation method for a block with type 'w' will get a callback function from the runtime
// as the final argument. This should be called by the 'w' block when it has finished its activities to 
// indicate to the runtime that execution can move on.

**Comment by darren-a** [comment]
I see that the 'w' block is asynchronous so I'm probably confused about how this works.

I still find this sentence has to follow: "This should be called to indicate that the block can stop waiting."

The 'w' block itself calls the callback function so is it perhaps clearer to say "This should be called to indicate that the 'w' block has finished waiting." ?

Possibly the term "waiting" is throwing me. The 'w' block itself is just "getting some stuff done that could take some time (more than a few ms)". It doesn't seem to be waiting so much as 'being waited for', no?

**Comment by Znapi** [comment]
The use of the terms "waiting" and "blocking" threw me off at first too. I never really got the hang of it until I started looking at the Scratch source code.

"w" and "R" blocks should be blocks that have to *wait* for an external service to give it a response, like a call to a web API. They aren't doing any processing, just waiting.

Since "w" and "R" blocks aren't doing anything other than waiting, they *block* execution of the stack. The stack can't move on to the next block even though the current one has finished doing stuff and is just waiting. " " and "r" blocks don't waste execution time like "w" and "R" blocks do by waiting.

**Comment by darren-a** [comment]
I understand what you're saying by this "They aren't doing any processing, just waiting.", but to my way of thinking the waiting that they're doing (for http or whatever) is actually processing - as in, they send a request and wait around for the response to come back. But it sounds like we just think slightly differently.

Do 'w' and 'R' blocks actually block execution of the stack? I thought the point of using these asynchronous methods is because it's recognized that they task they are doing (or starting off and then waiting for) are expected to take more than a few milliseconds, therefore we use an asynchronous block. The invocation method is called, the block starts off with its network task (for example), waits around for some seconds, then sends a callback to the runtime to indicate that results are ready...?

**Comment by darren-a** [comment]
I think I see what you meant. They're "locally blocking", yes, but they're not blocking in terms of the caller. That, to me, is the essence of what an asynchronous call is - you set it off and can safely forget about it (and move on) and wait for the callback.

I would define '  ' and 'r' as blocking and 'w' and 'R' as non-blocking. Perhaps we're both saying the same thing.

Thanks for the clarifications.

**Comment by Znapi** [comment]
I can definitely see why 'w' and 'R' could be called non-blocking. That is exactly what used to confuse me too. I just explained it in a way that conformed to what the wiki called blocking and non-blocking.

Also, I forgot that any block that takes more than a few milliseconds should be 'w' or 'R', whether it is just waiting or not, and now I am questioning what is actually waiting.

I do know that for the most part the runtime will execute consecutive ' ' and 'r' blocks without stopping. When it runs into a 'w' or 'R' block, it starts the block asynchronously, and then goes and executes a different stack's blocks(if another one is running). Perhaps it is the stack that is waiting rather than the block then.

I guess if your block takes longer to execute than it does to set up the callback function and switch to another stack, then you should use a 'w' or 'R' type.
