### ISSUE TITLE
Extension blocks are not loaded automatically when opening an sbx from an sb2

### ISSUE THREAD

**Issue by bobbybee** [LLK/scratchx#7]
Procedure to reproduce:

1) Create an sb2 with extensions imported
2) Import as an sbx on ScratchX
3) Import the extension on ScratchX (all works well)
4) Save as sbx
5) On a new tab, open the sbx
6) All extension blocks have the correct block spec, but they do not work and they do not appear in the More Blocks panel.
7) Repeating step 3 fixes step 6, but should be automatic (bug)

**Comment by cwillisf** [comment]
Hi @bobbybee,

I believe this was fixed with LLK/scratch-flash@a41e07e and LLK/scratch-flash@ce0a5e3 -- ce0a5e3 in particular. To convert a .sb2 file into a .sbx file you'll still need to use your steps 1-4, or you can use [this method](https://github.com/LLK/scratchx/issues/13#issuecomment-100924727), but I guess you figured that out. :)

Please reopen this issue if you find a situation where it still happens. Thanks!
